### ISSUE TITLE
Tests fail with current version of Gorums

### ISSUE THREAD

**Issue by meling** [relab/raft#10]
Looks like Gorums/Raft depends on API not available in relab/gorums repo.
```sh
# github.com/relab/raft/raftgorums
./outgoing.go:23:28: r.mem.get().SubError undefined (type *gorums.Configuration has no field or method SubError)
FAIL	github.com/relab/raft/raftgorums [build failed]
```

**Comment by s111** [comment]
Yes,  `relab/raft` is using `s111/gorums` (see [s111/rkv/glide.yaml#L28](https://github.com/s111/rkv/blob/13cab1b1381547226ff4d98b6a7a46c60b6127a2/glide.yaml#L28)) which has an error channel for listening to server errors. I don't think I actually used it for anything useful, so it shouldn't be too hard to change the dependency to `relab/gorums`.

**Comment by meling** [comment]
Closed with commit on gorums.
